/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSeasonTestRouteImport } from './routes/api/public/season-test'
import { Route as ApiPublicRandomClipRouteImport } from './routes/api/public/random-clip'
import { Route as ApiPublicQbPoolRouteImport } from './routes/api/public/qb-pool'
import { Route as ApiPublicNextClipRouteImport } from './routes/api/public/next-clip'
import { Route as ApiPublicClipCountRouteImport } from './routes/api/public/clip-count'
import { Route as ApiPublicClipRouteImport } from './routes/api/public/clip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeasonTestRoute = ApiPublicSeasonTestRouteImport.update({
  id: '/api/public/season-test',
  path: '/api/public/season-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRandomClipRoute = ApiPublicRandomClipRouteImport.update({
  id: '/api/public/random-clip',
  path: '/api/public/random-clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQbPoolRoute = ApiPublicQbPoolRouteImport.update({
  id: '/api/public/qb-pool',
  path: '/api/public/qb-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNextClipRoute = ApiPublicNextClipRouteImport.update({
  id: '/api/public/next-clip',
  path: '/api/public/next-clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipCountRoute = ApiPublicClipCountRouteImport.update({
  id: '/api/public/clip-count',
  path: '/api/public/clip-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClipRoute = ApiPublicClipRouteImport.update({
  id: '/api/public/clip',
  path: '/api/public/clip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/clip': typeof ApiPublicClipRoute
  '/api/public/clip-count': typeof ApiPublicClipCountRoute
  '/api/public/next-clip': typeof ApiPublicNextClipRoute
  '/api/public/qb-pool': typeof ApiPublicQbPoolRoute
  '/api/public/random-clip': typeof ApiPublicRandomClipRoute
  '/api/public/season-test': typeof ApiPublicSeasonTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/clip': typeof ApiPublicClipRoute
  '/api/public/clip-count': typeof ApiPublicClipCountRoute
  '/api/public/next-clip': typeof ApiPublicNextClipRoute
  '/api/public/qb-pool': typeof ApiPublicQbPoolRoute
  '/api/public/random-clip': typeof ApiPublicRandomClipRoute
  '/api/public/season-test': typeof ApiPublicSeasonTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/clip': typeof ApiPublicClipRoute
  '/api/public/clip-count': typeof ApiPublicClipCountRoute
  '/api/public/next-clip': typeof ApiPublicNextClipRoute
  '/api/public/qb-pool': typeof ApiPublicQbPoolRoute
  '/api/public/random-clip': typeof ApiPublicRandomClipRoute
  '/api/public/season-test': typeof ApiPublicSeasonTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/clip'
    | '/api/public/clip-count'
    | '/api/public/next-clip'
    | '/api/public/qb-pool'
    | '/api/public/random-clip'
    | '/api/public/season-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/clip'
    | '/api/public/clip-count'
    | '/api/public/next-clip'
    | '/api/public/qb-pool'
    | '/api/public/random-clip'
    | '/api/public/season-test'
  id:
    | '__root__'
    | '/'
    | '/api/public/clip'
    | '/api/public/clip-count'
    | '/api/public/next-clip'
    | '/api/public/qb-pool'
    | '/api/public/random-clip'
    | '/api/public/season-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicClipRoute: typeof ApiPublicClipRoute
  ApiPublicClipCountRoute: typeof ApiPublicClipCountRoute
  ApiPublicNextClipRoute: typeof ApiPublicNextClipRoute
  ApiPublicQbPoolRoute: typeof ApiPublicQbPoolRoute
  ApiPublicRandomClipRoute: typeof ApiPublicRandomClipRoute
  ApiPublicSeasonTestRoute: typeof ApiPublicSeasonTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/season-test': {
      id: '/api/public/season-test'
      path: '/api/public/season-test'
      fullPath: '/api/public/season-test'
      preLoaderRoute: typeof ApiPublicSeasonTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/random-clip': {
      id: '/api/public/random-clip'
      path: '/api/public/random-clip'
      fullPath: '/api/public/random-clip'
      preLoaderRoute: typeof ApiPublicRandomClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qb-pool': {
      id: '/api/public/qb-pool'
      path: '/api/public/qb-pool'
      fullPath: '/api/public/qb-pool'
      preLoaderRoute: typeof ApiPublicQbPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/next-clip': {
      id: '/api/public/next-clip'
      path: '/api/public/next-clip'
      fullPath: '/api/public/next-clip'
      preLoaderRoute: typeof ApiPublicNextClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clip-count': {
      id: '/api/public/clip-count'
      path: '/api/public/clip-count'
      fullPath: '/api/public/clip-count'
      preLoaderRoute: typeof ApiPublicClipCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clip': {
      id: '/api/public/clip'
      path: '/api/public/clip'
      fullPath: '/api/public/clip'
      preLoaderRoute: typeof ApiPublicClipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicClipRoute: ApiPublicClipRoute,
  ApiPublicClipCountRoute: ApiPublicClipCountRoute,
  ApiPublicNextClipRoute: ApiPublicNextClipRoute,
  ApiPublicQbPoolRoute: ApiPublicQbPoolRoute,
  ApiPublicRandomClipRoute: ApiPublicRandomClipRoute,
  ApiPublicSeasonTestRoute: ApiPublicSeasonTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
